const TOASTIFY_SUCCESS = "TOASTIFY_SUCCESS";
const TOASTIFY_ERROR = "TOASTIFY_ERROR";
const TOASTIFY_WARNING = "TOASTIFY_WARNING";
const TOASTIFY_INFO = "TOASTIFY_INFO";
const TOASTIFY_DEFAULT = "TOASTIFY_DEFAULT";
const TOASTIFY_TIME_OUT = 2 * 1000;

export { TOASTIFY_SUCCESS, TOASTIFY_ERROR, TOASTIFY_WARNING, TOASTIFY_INFO, TOASTIFY_TIME_OUT, TOASTIFY_DEFAULT }